# general
setw -g xterm-keys on
set -s escape-time 0
set -sg repeat-time 300
set -s focus-events on
set -sg exit-empty on

setenv -g termapp tmux

set -q -g status-utf8 on
setw -q -g utf8 on

set -g visual-activity off
setw -g monitor-activity off
setw -g monitor-bell off

set -g history-limit 10000

# color
set -g default-terminal screen-256color
set-option -ga terminal-overrides ",*256col*:Tc" 

# prefix key
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix


# window navigation
unbind n
unbind p
unbind 1
unbind 2
unbind 3
unbind 4
unbind 5
unbind 6
unbind 7
unbind 8
unbind 9
unbind 0
bind -r C-p previous-window
bind -r C-n next-window

bind-key 1 select-window -t 1
bind-key 2 select-window -t 2
bind-key 3 select-window -t 3
bind-key 4 select-window -t 4
bind-key 5 select-window -t 5
bind-key 6 select-window -t 6
bind-key 7 select-window -t 7
bind-key 8 select-window -t 8
bind-key 9 select-window -t 9


bind-key ! join-pane -t :1
bind-key @ join-pane -t :2
bind-key '#' join-pane -t :3
bind-key '$' join-pane -t :4
bind-key % join-pane -t :5
bind-key ^ join-pane -t :6
bind-key & join-pane -t :7
bind-key * join-pane -t :8
bind-key ( join-pane -t :9


# mouse
set -g mouse on

# split in direction
bind h split-window -hb -c "#(pane_current_path)"
bind j split-window -v  -c "#(pane_current_path)"
bind k split-window -vb -c "#(pane_current_path)"
bind l split-window -h  -c "#(pane_current_path)"


# count from 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on


# PLUGINS

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

set -g status-position top
set -g @tmux_power_theme 'default'

run '~/.tmux/plugins/tpm/tpm'
