add_newline = true

[aws]
symbol = "\ue33d  "
format = "\\[[$symbol($profile)(\\($region\\))(\\[$duration\\])]($style)\\]"

[buf]
symbol = "\uf49d "

[c]
symbol = "\ue61e "
format = "\\[[$symbol($version(-$name))]($style)\\]"

[conda]
symbol = "\uf10c "
format = "\\[[$symbol$environment]($style)\\]"

[dart]
symbol = "\ue798 "
format = "\\[[$symbol($version)]($style)\\]"

[directory]
read_only = " \U000f033e"
format = " [$path]($style)[$read_only]($read_only_style) "

[docker_context]
symbol = "\uf308 "
format = "\\[[$symbol$context]($style)\\]"

[elixir]
symbol = "\ue275 "
format = "\\[[$symbol($version \\(OTP $otp_version\\))]($style)\\]"

[elm]
symbol = "\ue62c "
format = "\\[[$symbol($version)]($style)\\]"

[fossil_branch]
symbol = "\uf418 "
format = "\\[[$symbol$branch]($style)\\]"

[git_branch]
symbol = "\uf418 "
format = "\\[[$symbol$branch]($style)\\]"

[golang]
symbol = "\ue627 "
format = "\\[[$symbol($version)]($style)\\]"

[guix_shell]
symbol = "\uf325 "
format = "\\[[$symbol]($style)\\]"

[haskell]
symbol = "\ue777 "
format = "\\[[$symbol($version)]($style)\\]"

[haxe]
symbol = "\ue666 "
format = "\\[[$symbol($version)]($style)\\]"

[hg_branch]
symbol = "\uf418 "
format = "\\[[$symbol$branch]($style)\\]"

[hostname]
ssh_symbol = "\ueb01 "

[java]
symbol = "\ue256 "
format = "\\[[$symbol($version)]($style)\\]"

[julia]
symbol = "\ue624 "
format = "\\[[$symbol($version)]($style)\\]"

[lua]
symbol = "\ue620 "
format = "\\[[$symbol($version)]($style)\\]"

[memory_usage]
symbol = "\U000f035b "
format = "\\[$symbol[$ram( | $swap)]($style)\\]"

[meson]
symbol = "\U000f0537 "
format = "\\[[$symbol$project]($style)\\]"

[nim]
symbol = "\U000f01a5 "
format = "\\[[$symbol($version)]($style)\\]"

[nix_shell]
symbol = "\uf313 "
format = "\\[[$symbol$state( \\($name\\))]($style)\\]"

[nodejs]
symbol = "\ue718 "
format = "\\[[$symbol($version)]($style)\\]"

[os]
format = "\\[[$symbol]($style)\\]"

[package]
symbol = "\U000f03d7 "
format = "\\[[$symbol$version]($style)\\]"

[pijul_channel]
symbol = "\uf418 "
format = "\\[[$symbol$channel]($style)\\]"

[python]
symbol = "\ue235 "
format = "\\[[${symbol}${pyenv_prefix}(${version})(\\($virtualenv\\))]($style)\\]"

[rlang]
symbol = "\U000f07d4 "

[ruby]
symbol = "\ue791 "
format = "\\[[$symbol($version)]($style)\\]"

[rust]
symbol = "\ue7a8 "
format = "\\[[$symbol($version)]($style)\\]"

[scala]
symbol = "\ue737 "
format = "\\[[$symbol($version)]($style)\\]"

[bun]
format = "\\[[$symbol($version)]($style)\\]"

[cmake]
format = "\\[[$symbol($version)]($style)\\]"

[cmd_duration]
format = "\\[[⏱ $duration]($style)\\]"

[cobol]
format = "\\[[$symbol($version)]($style)\\]"

[crystal]
format = "\\[[$symbol($version)]($style)\\]"

[daml]
format = "\\[[$symbol($version)]($style)\\]"

[deno]
format = "\\[[$symbol($version)]($style)\\]"

[dotnet]
format = "\\[[$symbol($version)(🎯 $tfm)]($style)\\]"

[erlang]
format = "\\[[$symbol($version)]($style)\\]"

[fennel]
format = "\\[[$symbol($version)]($style)\\]"

[gcloud]
format = "\\[[$symbol$account(@$domain)(\\($region\\))]($style)\\]"

[git_status]
format = "([\\[$all_status$ahead_behind\\]]($style))"

[gradle]
format = "\\[[$symbol($version)]($style)\\]"

[helm]
format = "\\[[$symbol($version)]($style)\\]"

[kotlin]
format = "\\[[$symbol($version)]($style)\\]"

[kubernetes]
format = "\\[[$symbol$context( \\($namespace\\))]($style)\\]"

[ocaml]
format = "\\[[$symbol($version)(\\($switch_indicator$switch_name\\))]($style)\\]"

[opa]
format = "\\[[$symbol($version)]($style)\\]"

[openstack]
format = "\\[[$symbol$cloud(\\($project\\))]($style)\\]"

[perl]
format = "\\[[$symbol($version)]($style)\\]"

[php]
format = "\\[[$symbol($version)]($style)\\]"

[pulumi]
format = "\\[[$symbol$stack]($style)\\]"

[purescript]
format = "\\[[$symbol($version)]($style)\\]"

[raku]
format = "\\[[$symbol($version-$vm_version)]($style)\\]"

[red]
format = "\\[[$symbol($version)]($style)\\]"

[spack]
format = "\\[[$symbol$environment]($style)\\]"

[sudo]
format = "\\[[as $symbol]($style)\\]"

[swift]
format = "\\[[$symbol($version)]($style)\\]"

[terraform]
format = "\\[[$symbol$workspace]($style)\\]"

[time]
format = "\\[[$time]($style)\\]"

[username]
format = "\\[[$user]($style)\\]"

[vagrant]
format = "\\[[$symbol($version)]($style)\\]"

[vlang]
format = "\\[[$symbol($version)]($style)\\]"

[zig]
format = "\\[[$symbol($version)]($style)\\]"

[solidity]
format = "\\[[$symbol($version)]($style)\\]"

[os.symbols]
Alpaquita = "\ueaa2 "
Alpine = "\uf300 "
Amazon = "\uf270 "
Android = "\uf17b "
Arch = "\uf303 "
Artix = "\uf31f "
CentOS = "\uf304 "
Debian = "\uf306 "
DragonFly = "\ue28e "
Emscripten = "\uf205 "
EndeavourOS = "\uf197 "
Fedora = "\uf30a "
FreeBSD = "\uf30c "
Garuda = "\U000f06d3 "
Gentoo = "\uf30d "
HardenedBSD = "\U000f078c "
Illumos = "\U000f0238 "
Linux = "\uf31a "
Mabox = "\ueb29 "
Macos = "\uf302 "
Manjaro = "\uf312 "
Mariner = "\uf1cd "
MidnightBSD = "\uf186 "
Mint = "\uf30e "
NetBSD = "\uf024 "
NixOS = "\uf313 "
OpenBSD = "\U000f023a "
openSUSE = "\uf314 "
OracleLinux = "\U000f0337 "
Pop = "\uf32a "
Raspbian = "\uf315 "
Redhat = "\uf316 "
RedHatEnterprise = "\uf316 "
Redox = "\U000f0018 "
Solus = "\U000f0833 "
SUSE = "\uf314 "
Ubuntu = "\uf31b "
Unknown = "\uf22d "
Windows = "\U000f0372 "
